### PR TITLE
Adding more sprites from Dongwaiver, Erin and valterak, and deleting old unused sprites.

### PR DESCRIPTION
**Pull request by TheBimmer231**
**Additions and change:**
-Newest weapon addition.
-Commissar, investigator and both commanders.
-More objects.
-Merges storage_slots and storage_slot-addon folders
-tileable tables

### CODE REVIEW

**Comment by TheBimmer231** [comment]
@Quantomicus Do not merge until I get the latest inhand sprites from Dongwaiver, and when Memeoji comes out of hibernation.

**Comment by TheBimmer231** [comment]
Oh wow, my first conflict, I don't know what that means.

**Comment by TheBimmer231** [comment]
Conflict fixed

**Comment by TheBimmer231** [comment]
my git journey is very bumpy, who the fuck is travis and why doesn't he like my PR

**Comment by Quantomicus** [comment]
Is this still WIP?

**Comment by Quantomicus** [comment]
@TheBimmer231 Status?

**Pull request closed without merging**
